export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    SEND_OTP: "/auth/send-otp",
    VERIFY_OTP: "/auth/verify-otp",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
    ME: "/auth/me",
    PROFILE: "/auth/profile",
    LOGOUT: "/auth/logout",
  },
  ADDRESSES: {
    BASE: "/addresses",
    BY_ID: (id: string | number) => `/addresses/${id}`,
    DEFAULT: (id: string | number) => `/addresses/${id}/default`,
  },
  CATEGORIES: {
    BASE: "/categories",
    BY_ID: (id: string | number) => `/categories/${id}`,
    STATUS: (id: string | number) => `/categories/${id}/status`,
    SORT_ORDER: (id: string | number) => `/categories/${id}/sort-order`,
  },
  SUB_CATEGORIES: {
    BASE: "/sub-categories",
    BY_ID: (id: string | number) => `/sub-categories/${id}`,
    BY_CATEGORY: (catId: string | number) => `/sub-categories/category/${catId}`,
    STATUS: (id: string | number) => `/sub-categories/${id}/status`,
  },
  BRANDS: {
    BASE: "/brands",
    BY_ID: (id: string | number) => `/brands/${id}`,
    STATUS: (id: string | number) => `/brands/${id}/status`,
  },
  COLLECTIONS: {
    BASE: "/collections",
    BY_ID: (id: string | number) => `/collections/${id}`,
    STATUS: (id: string | number) => `/collections/${id}/status`,
  },
  COLORS: {
    BASE: "/colors",
    BY_ID: (id: string | number) => `/colors/${id}`,
  },
  SIZES: {
    BASE: "/sizes",
    BY_ID: (id: string | number) => `/sizes/${id}`,
  },
  PRODUCTS: {
    BASE: "/products",
    BY_ID: (id: string | number) => `/products/${id}`,
    BY_SLUG: (slug: string) => `/products/slug/${slug}`,
    STATUS: (id: string | number) => `/products/${id}/status`,
    IMAGES: (productId: string | number) => `/products/${productId}/images`,
    IMAGE_PRIMARY: (productId: string | number, imageId: string | number) => `/products/${productId}/images/${imageId}/primary`,
    VARIANTS: (productId: string | number) => `/products/${productId}/variants`,
    VARIANT_STOCK: (productId: string | number, variantId: string | number) => `/products/${productId}/variants/${variantId}/stock`,
  },
  PRODUCT_ATTRIBUTES: {
    BASE: "/product-attributes",
    BY_ID: (id: string | number) => `/product-attributes/${id}`,
  },
  PRODUCT_ATTRIBUTE_VALUES: {
    BASE: "/product-attribute-values",
    BY_PRODUCT: (productId: string | number) => `/product-attribute-values/product/${productId}`,
  },
  CART: {
    BASE: "/cart",
    ITEMS: "/cart/items",
    BY_ITEM: (itemId: string | number) => `/cart/items/${itemId}`,
    COUNT: "/cart/count",
    SUMMARY: "/cart/summary",
  },
  WISHLIST: {
    BASE: "/wishlist",
    ITEMS: "/wishlist/items",
    BY_PRODUCT: (productId: string | number) => `/wishlist/items/${productId}`,
    CHECK: (productId: string | number) => `/wishlist/check/${productId}`,
  },
  ORDERS: {
    BASE: "/orders",
    BY_ID: (id: string | number) => `/orders/${id}`,
    CANCEL: (id: string | number) => `/orders/${id}/cancel`,
    TIMELINE: (id: string | number) => `/orders/${id}/status-history`,
  },
  PAYMENTS: {
    BASE: "/payments",
    VERIFY: "/payments/verify",
    BY_ID: (id: string | number) => `/payments/${id}`,
    BY_ORDER: (orderId: string | number) => `/payments/order/${orderId}`,
  },
  REVIEWS: {
    BASE: "/reviews",
    BY_PRODUCT: (productId: string | number) => `/reviews/product/${productId}`,
    SUMMARY: (productId: string | number) => `/reviews/product/${productId}/summary`,
    MY: "/reviews/my",
    REPLY: (id: string | number) => `/reviews/${id}/reply`,
    APPROVE: (id: string | number) => `/reviews/${id}/approve`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    BY_ID: (id: string | number) => `/notifications/${id}`,
    READ: (id: string | number) => `/notifications/${id}/read`,
    READ_ALL: "/notifications/read-all",
    SUMMARY: "/notifications/summary",
  },
  SELLER: {
    PROFILE: "/seller-profile",
    PROFILE_BY_ID: (id: string | number) => `/seller-profile/${id}`,
    ORDERS: "/seller-orders",
    ORDER_BY_ID: (id: string | number) => `/seller-orders/${id}`,
    ORDER_STATUS: (id: string | number) => `/seller-orders/${id}/status`,
    ORDER_PACKAGES: (id: string | number) => `/seller-orders/${id}/packages`,
    PACKAGE_BY_ID: (id: string | number) => `/seller-orders/packages/${id}`,
    ORDER_HISTORY: (id: string | number) => `/seller-orders/${id}/history`,
    DASHBOARD_OVERVIEW: "/seller-dashboard/overview",
    DASHBOARD_REVENUE: "/seller-dashboard/revenue",
    DASHBOARD_PRODUCTS: "/seller-dashboard/products",
    DASHBOARD_RECENT_ORDERS: "/seller-dashboard/recent-orders",
    DASHBOARD_TOP_PRODUCTS: "/seller-dashboard/top-products",
    DASHBOARD_REVIEWS: "/seller-dashboard/recent-reviews",
    DASHBOARD_NOTIFICATIONS: "/seller-dashboard/notifications",
    DASHBOARD_CHARTS: "/seller-dashboard/charts",
    SETTLEMENTS: "/seller/settlements",
    SETTLEMENTS_HISTORY: "/seller/settlements/history",
    SETTLEMENT_BY_ID: (id: string | number) => `/seller/settlements/${id}`,
    ANALYTICS_OVERVIEW: "/seller-analytics/overview",
    ANALYTICS_SALES_TRENDS: "/seller-analytics/sales-trends",
    ANALYTICS_CUSTOMER_INSIGHTS: "/seller-analytics/customer-insights",
    ANALYTICS_PRODUCT_INSIGHTS: "/seller-analytics/product-insights",
    ANALYTICS_REVENUE_INSIGHTS: "/seller-analytics/revenue-insights",
    ANALYTICS_FORECAST: "/seller-analytics/forecast",
    REPORTS_SALES: "/seller-reports/sales",
    REPORTS_ORDERS: "/seller-reports/orders",
    REPORTS_PRODUCTS: "/seller-reports/products",
    REPORTS_CUSTOMERS: "/seller-reports/customers",
    REPORTS_SETTLEMENTS: "/seller-reports/settlements",
    REPORTS_EXPORTS: "/seller-reports/exports",
    SHIPMENTS: "/shipments",
  },
  ADMIN: {
    USERS: "/admin/users",
    USER_STATUS: (id: string | number) => `/admin/users/${id}/status`,
    SELLERS: "/admin/sellers",
    SELLER_STATUS: (id: string | number) => `/admin/sellers/${id}/status`,
    PRODUCTS: "/admin/products",
    PRODUCT_APPROVAL: (id: string | number) => `/admin/products/${id}/approval`,
    ORDERS: "/admin/orders",
    PAYMENTS: "/admin/payments",
    RETURNS: "/admin/returns",
    SETTLEMENTS: "/admin/settlements",
    HOMEPAGE_SUMMARY: "/admin/homepage/summary",
    REPORTS_SALES: "/admin/reports/sales",
  },
  INVOICES: {
    BASE: "/invoices",
    BY_ID: (id: string | number) => `/invoices/${id}`,
    DOWNLOAD: (id: string | number) => `/invoices/${id}/download`,
  },
  SHIPMENTS: {
    BASE: "/shipments",
    BY_ID: (id: string | number) => `/shipments/${id}`,
    TRACK: (id: string | number) => `/shipments/${id}/track`,
  },
  SEARCH: "/search",
  STATIC: {
    COUNTRIES: "/static/countries",
    STATES: "/static/states",
    CITIES: "/static/cities",
  },
} as const;
