export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    SEND_OTP: "/auth/send-otp",
    VERIFY_OTP: "/auth/verify-otp",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
    ME: "/auth/me",
  },
  ADDRESSES: {
    BASE: "/addresses",
    BY_ID: (id: string | number) => `/addresses/${id}`,
    DEFAULT: (id: string | number) => `/addresses/${id}/default`,
  },
  CATEGORIES: {
    BASE: "/categories",
    BY_ID: (id: string | number) => `/categories/${id}`,
    STATUS: (id: string | number) => `/categories/${id}/status`,
    SORT_ORDER: (id: string | number) => `/categories/${id}/sort-order`,
  },
  SUB_CATEGORIES: {
    BASE: "/sub-categories",
    BY_ID: (id: string | number) => `/sub-categories/${id}`,
    BY_CATEGORY: (catId: string | number) => `/sub-categories/category/${catId}`,
    STATUS: (id: string | number) => `/sub-categories/${id}/status`,
  },
  BRANDS: {
    BASE: "/brands",
    BY_ID: (id: string | number) => `/brands/${id}`,
    STATUS: (id: string | number) => `/brands/${id}/status`,
  },
  COLLECTIONS: {
    BASE: "/collections",
    BY_ID: (id: string | number) => `/collections/${id}`,
    STATUS: (id: string | number) => `/collections/${id}/status`,
  },
  COLORS: {
    BASE: "/colors",
    BY_ID: (id: string | number) => `/colors/${id}`,
  },
  SIZES: {
    BASE: "/sizes",
    BY_ID: (id: string | number) => `/sizes/${id}`,
  },
  PRODUCTS: {
    BASE: "/products",
    BY_ID: (id: string | number) => `/products/${id}`,
    BY_SLUG: (slug: string) => `/products/slug/${slug}`,
    STATUS: (id: string | number) => `/products/${id}/status`,
    IMAGES: (productId: string | number) => `/products/${productId}/images`,
    IMAGE_PRIMARY: (productId: string | number, imageId: string | number) => `/products/${productId}/images/${imageId}/primary`,
    VARIANTS: (productId: string | number) => `/products/${productId}/variants`,
    VARIANT_STOCK: (productId: string | number, variantId: string | number) => `/products/${productId}/variants/${variantId}/stock`,
  },
  CART: {
    BASE: "/cart",
    ITEMS: "/cart/items",
    BY_ITEM: (itemId: string | number) => `/cart/items/${itemId}`,
    COUNT: "/cart/count",
    SUMMARY: "/cart/summary",
  },
  WISHLIST: {
    ITEMS: "/wishlist/items",
    BY_PRODUCT: (productId: string | number) => `/wishlist/items/${productId}`,
    CHECK: (productId: string | number) => `/wishlist/check/${productId}`,
  },
  ORDERS: {
    BASE: "/orders",
    BY_ID: (id: string | number) => `/orders/${id}`,
    CANCEL: (id: string | number) => `/orders/${id}/cancel`,
    TIMELINE: (id: string | number) => `/orders/${id}/status-history`,
  },
  PAYMENTS: {
    BASE: "/payments",
    VERIFY: "/payments/verify",
    BY_ID: (id: string | number) => `/payments/${id}`,
    BY_ORDER: (orderId: string | number) => `/payments/order/${orderId}`,
  },
  REVIEWS: {
    BASE: "/reviews",
    BY_PRODUCT: (productId: string | number) => `/reviews/product/${productId}`,
    SUMMARY: (productId: string | number) => `/reviews/product/${productId}/summary`,
    MY: "/reviews/my",
    REPLY: (id: string | number) => `/reviews/${id}/reply`,
    APPROVE: (id: string | number) => `/reviews/${id}/approve`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    BY_ID: (id: string | number) => `/notifications/${id}`,
    READ: (id: string | number) => `/notifications/${id}/read`,
    READ_ALL: "/notifications/read-all",
    SUMMARY: "/notifications/summary",
  },
  SELLER: {
    PROFILE: "/sellers/profile",
    ORDERS: "/seller-orders",
    ORDER_BY_ID: (id: string | number) => `/seller-orders/${id}`,
    ORDER_STATUS: (id: string | number) => `/seller-orders/${id}/status`,
    DASHBOARD_SUMMARY: "/seller-dashboard/summary",
    DASHBOARD_REVENUE: "/seller-dashboard/revenue",
    DASHBOARD_STOCK_ALERTS: "/seller-dashboard/stock-alerts",
    SETTLEMENTS: "/seller-settlements",
    SHIPMENTS: "/shipments/seller",
    RETURNS: "/returns/seller",
  },
  ADMIN: {
    USERS: "/admin/users",
    USER_STATUS: (id: string | number) => `/admin/users/${id}/status`,
    SELLERS: "/admin/sellers",
    SELLER_STATUS: (id: string | number) => `/admin/sellers/${id}/status`,
    PRODUCTS: "/admin/products",
    PRODUCT_APPROVAL: (id: string | number) => `/admin/products/${id}/approval`,
    ORDERS: "/admin/orders",
    PAYMENTS: "/admin/payments",
    RETURNS: "/admin/returns",
    SETTLEMENTS: "/admin/settlements",
    HOMEPAGE_SUMMARY: "/admin/homepage/summary",
    REPORTS_SALES: "/admin/reports/sales",
  },
  SEARCH: "/search",
  STATIC: {
    COUNTRIES: "/static/countries",
    STATES: "/static/states",
    CITIES: "/static/cities",
  },
} as const;
